### ISSUE TITLE
Cannot initialize on latest flutter dev, iOS simulator

### ISSUE THREAD

**Issue by SteveAlexander** [Dana-Ferguson/time_machine#10]
I get an error using timemachine in a flutter app. I've tested this so far on an iOS simulator.

What happens is, when I initialize TimeMachine, it is unable to load the culture from the rootbundle.

```
      await TimeMachine.initialize({
        'rootBundle': rootBundle
      });
```

The error is:

```
Unable to load asset: packages/time_machine/data/cultures/-.bin
```

This occurs because `io.Platform.localeName` is returning `_` (see https://github.com/flutter/flutter/issues/23241 ), and the TimeMachine logic in `vm.dart` doesn't deal with this well.

```
    var cultureId = io.Platform.localeName?.split('.')?.first?.replaceAll('_', '-') ?? 'en-US';
    var culture = await Cultures.getCulture(cultureId);
```

```
$ flutter doctor -v
[✓] Flutter (Channel master, v0.10.1-pre.77, on Mac OS X 10.13.6 17G2307, locale
    en-GB)
    • Flutter version 0.10.1-pre.77 at /Users/steve/code/flutter
    • Framework revision 5193affb27 (2 hours ago), 2018-10-18 04:15:02 -0400
    • Engine revision cc2ec365b7
    • Dart version 2.1.0-dev.7.1.flutter-b99bcfd309

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/steve/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.0, Build version 10A255
    • ios-deploy 2.0.0
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 26.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build
      1.8.0_152-release-1024-b01)

[✓] VS Code (version 1.27.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.18.0

[✓] Connected device (1 available)
    • iPhone X • EF563F7A-675E-4CF8-AFFF-E518AF44A1F2 • ios • iOS 12.0
      (simulator)

• No issues found!
```

**Comment by asue** [comment]
I also get this error, but only when building a release version of it.  I am on the beta channel of flutter though.

```
[✓] Flutter (Channel beta, v0.9.4, on Mac OS X 10.14 18A391, locale en-US)
    • Flutter version 0.9.4 at /Users/AlSue/Documents/dev/flutter
    • Framework revision f37c235c32 (5 weeks ago), 2018-09-25 17:45:40 -0400
    • Engine revision 74625aed32
    • Dart version 2.1.0-dev.5.0.flutter-a2eb050044

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.1)
    • Android SDK at /Users/AlSue/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.1
    • ANDROID_HOME = /Users/AlSue/Library/Android
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.2
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] VS Code (version 1.28.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.19.0

[✓] Connected devices (1 available)
    • iPad Air 2      • 2A5DA3AB-AB03-4B3E-8D69-DDCBD8722A83     • ios • iOS 12.1 (simulator)
```

**Comment by Pareshoct7** [comment]
I also get a similar error.


```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
Unable to load asset: packages/time_machine/data/cultures/null.bin
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      _FlutterMachineIO.getBinary (package:time_machine/src/platforms/vm.dart:44:43)
<asynchronous suspension>
#2      CultureLoader.getCulture (package:time_machine/src/text/globalization/culture_io.dart:70:76)
<asynchronous suspension>
#3      Cultures.getCulture (package:time_machine/src/text/globalization/culture.dart:27:75)
<asynchronous suspension>
#4      TimeMachine.initialize (package:time_machine/src/platforms/vm.dart:97:34)
<asynchronous suspension>
#5      initialize (package:time_machine/src/platforms/vm.dart:69:22)
#6      TimeMachine.initialize (package:time_machine/time_machine.dart:100:12)
#7      setUp (package:flutter_app/main.dart:38:21)
<asynchronous suspension>
#8      main (package:flutter_app/main.dart:29:9)
<asynchronous suspension>
#9   <…>

```

**Comment by SteveAlexander** [comment]
reason is, `io.Platform.localeName` returns the string `"null"`, rather than an actual null.

**Comment by SteveAlexander** [comment]
There's an additional problem. If I hack in converting `"null"` to `null`, there's another problem in `culture_io.dart`, around line 69.

```
  Future<Culture> getCulture(String cultureId) async {
    return _cache[cultureId] ??= _cultureFromBinary(await PlatformIO.local.getBinary('cultures', '$cultureId.bin'));
  }
```

The problem is that if `cultureId` is `null`, we look for an asset called `null.bin`.

A quick fix would be:

```
  Future<Culture> getCulture(String cultureId) async {
    if (cultureId == null) return null;
    return _cache[cultureId] ??= _cultureFromBinary(await PlatformIO.local.getBinary('cultures', '$cultureId.bin'));
  }
```
