### ISSUE TITLE
Unexpected locales/cultures are not handled gracefully

### ISSUE THREAD

**Issue by jbg** [Dana-Ferguson/time_machine#13]
With the iPhone's separation of "language" and "region" it's possible to get locales like "en-CN". At present (tested on 0.9.7) it's not possible to initialise TimeMachine if the locale is not one that TimeMachine ships:

```
[VERBOSE-2:shell.cc(184)] Dart Error: Unhandled exception:
Unable to load asset: packages/time_machine/data/cultures/en-CN.bin
#0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:221:7)
<asynchronous suspension>
#1      _FlutterMachineIO.getBinary (package:time_machine/src/platforms/vm.dart:44:43)
<asynchronous suspension>
#2      CultureLoader.getCulture (package:time_machine/src/text/globalization/culture_io.dart:71:76)
<asynchronous suspension>
#3      Cultures.getCulture (package:time_machine/src/text/globalization/culture.dart:27:75)
<asynchronous suspension>
#4      TimeMachine.initialize (package:time_machine/src/platforms/vm.dart:97:34)
<asynchronous suspension>
#5      initialize (package:time_machine/src/platforms/vm.dart:69:22)
#6      TimeMachine.initialize (package:time_machine/time_machine.dart:100:12)
#7      main (package:------/main.dart:22:21)
<asynchronous suspension>
#8      _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:289:19)
#9      _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:171:12)
```

**Comment by Dana-Ferguson** [comment]
Looking through the CLDR data, it doesn't seem to exist.
https://github.com/unicode-cldr/cldr-localenames-full/tree/master/main

I wonder how other iPhone's programs handle it? (barring a better answer, I'm going to have to just default to defaulting to `en`)

**Comment by Dana-Ferguson** [comment]
Fixed in https://github.com/Dana-Ferguson/time_machine/commit/429257c0710fc7673718cd5c9dbbca399e9bc1fc .
I went with the quick fix. `en-CN` will become `en`. I published the fix in version 0.9.8. Let me know if the fix works for you and we'll close the issue.
