### ISSUE TITLE
Compile error when run on mobile

### ISSUE THREAD

**Issue by idkhanhvo272** [Dana-Ferguson/time_machine#20]
Flutter crash report; please file at https://github.com/flutter/flutter/issues.

## command

flutter run

## exception

ProcessException: ProcessException: Process "/usr/bin/xcrun" exited abnormally:
An error was encountered processing the command (domain=IXUserPresentableErrorDomain, code=1):
This app could not be installed at this time.
Could not hardlink copy /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Containers/Bundle/Application/B77C4569-51F2-4B02-8B1D-A567C778F2D3/Runner.app to /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Library/Caches/com.apple.mobile.installd.staging/temp.ERpbay/extracted/Payload/Runner.app with manifest /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Library/Caches/com.apple.mobile.installd.staging/temp.ERpbay/extracted/com.apple.deltainstallcommands.com.example.flutterExample
Could not hardlink copy /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Containers/Bundle/Application/B77C4569-51F2-4B02-8B1D-A567C778F2D3/Runner.app to /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Library/Caches/com.apple.mobile.installd.staging/temp.ERpbay/extracted/Payload/Runner.app with manifest /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Library/Caches/com.apple.mobile.installd.staging/temp.ERpbay/extracted/com.apple.deltainstallcommands.com.example.flutterExample
Underlying error (domain=MIInstallerErrorDomain, code=8):
	Could not hardlink copy /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Containers/Bundle/Application/B77C4569-51F2-4B02-8B1D-A567C778F2D3/Runner.app to /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Library/Caches/com.apple.mobile.installd.staging/temp.ERpbay/extracted/Payload/Runner.app with manifest /Users/kv/Library/Developer/CoreSimulator/Devices/3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C/data/Library/Caches/com.apple.mobile.installd.staging/temp.ERpbay/extracted/com.apple.deltainstallcommands.com.example.flutterExample
  Command: /usr/bin/xcrun simctl install 3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C /Users/kv/Downloads/time_machine-master/example/flutter_example/build/ios/iphonesimulator/Runner.app

```
#0      runCheckedAsync (package:flutter_tools/src/base/process.dart:259:7)
<asynchronous suspension>
#1      SimControl.install (package:flutter_tools/src/ios/simulators.dart:128:16)
#2      IOSSimulator._setupUpdatedApplicationBundle (package:flutter_tools/src/ios/simulators.dart:415:31)
<asynchronous suspension>
#3      IOSSimulator.startApp (package:flutter_tools/src/ios/simulators.dart:315:15)
<asynchronous suspension>
#4      FlutterDevice.runHot (package:flutter_tools/src/resident_runner.dart:371:54)
#5      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:77:64)
#6      _rootRunUnary (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#8      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#9      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#10     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#11     Future._complete (dart:async/future_impl.dart:473:7)
#12     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#13     _AsyncAwaitCompleter.complete.<anonymous closure> (dart:async-patch/async_patch.dart:33:20)
#14     _rootRun (dart:async/zone.dart:1120:38)
#15     _CustomZone.run (dart:async/zone.dart:1021:19)
#16     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#17     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#18     _rootRun (dart:async/zone.dart:1124:13)
#19     _CustomZone.run (dart:async/zone.dart:1021:19)
#20     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#21     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#22     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#23     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#24     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#25     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)
```

## flutter doctor

```
[32m[✓][39m Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G87, locale en-US)
    [32m•[39m Flutter version 1.7.8+hotfix.4 at /Users/kv/working/flutter
    [32m•[39m Framework revision 20e59316b8 (4 weeks ago), 2019-07-18 20:04:33 -0700
    [32m•[39m Engine revision fee001c93f
    [32m•[39m Dart version 2.4.0

[32m[✓][39m Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    [32m•[39m Android SDK at /Users/kv/Library/Android/sdk
    [32m•[39m Android NDK location not configured (optional; useful for native profiling support)
    [32m•[39m Platform android-29, build-tools 29.0.0
    [32m•[39m Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    [32m•[39m All Android licenses accepted.

[32m[✓][39m Xcode - develop for iOS and macOS (Xcode 10.3)
    [32m•[39m Xcode at /Applications/Xcode.app/Contents/Developer
    [32m•[39m Xcode 10.3, Build version 10G8
    [32m•[39m CocoaPods version 1.7.5

[32m[✓][39m iOS tools - develop for iOS devices
    [32m•[39m ios-deploy 1.9.4

[32m[✓][39m Android Studio (version 3.4)
    [32m•[39m Android Studio at /Applications/Android Studio.app/Contents
    [32m•[39m Flutter plugin version 37.0.1
    [32m•[39m Dart plugin version 183.6270
    [32m•[39m Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[33m[!][39m IntelliJ IDEA Ultimate Edition (version 2019.2)
    [32m•[39m IntelliJ at /Applications/IntelliJ IDEA.app
    [31m✗[39m Flutter plugin not installed; this adds Flutter specific functionality.
    [31m✗[39m Dart plugin not installed; this adds Dart specific functionality.
    [32m•[39m For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[32m[✓][39m Connected device (1 available)
    [32m•[39m iPhone Xʀ • 3413F5AE-064D-49B6-A6F8-C6A2C09D8E0C • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

[33m![39m Doctor found issues in 1 category.
```

**Comment by idkhanhvo272** [comment]
Help me solve the problems on the above

**Comment by Dana-Ferguson** [comment]
I worked on web today, I'll work on this tomorrow, but a quick look over your output, I'm not sure time_machine is an issue here.

You might want to look here: https://github.com/flutter/flutter/issues/24695

Does that help you at all?
